# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Simple Blog Theme
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/jekyll-theme-simple-blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://lorepirri.gitlab.io" # change this to the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Make sure to exclude 'vendor' from the build
exclude: [vendor, "Gemfile", "Gemfile.lock"]

# permalink: /:categories/:year/:month/:day/:title.html
# none is equivalent to /:title.html
# https://jekyllrb.com/docs/permalinks
permalink: /:title.html

google_analytics:

# jekyll-theme-simple-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
jekyll-theme-simple-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

header:
  image: /assets/patterns/symphony.png

# social
author: "Lore Pirri"
image: /assets/patterns/seigaiha.png
twitter:
  username: lorepirri
instagram_username: pirriontheroad

#  site:
facebook:
  publisher_id: 1474191545979552 #1592372034171500 #
  profile_id: 1474191545979552
  app_id: 126080721296732 #1798910940422432 #
  #admins: 1474191545979552
  authors: [1474191545979552]
  #pixelcode: 1670622619859349

# github on post
github:
  owner_url: https://github.com/lorepirri
#  project_tagline: "here short descr"
#  is_project_page: true
#  show_downloads: true
#  repository_url: https://github.com/lorepirri/jekyll-theme-simple-blog
#  zip_url: https://github.com/lorepirri/jekyll-theme-simple-blog/archive/master.zip
#  tar_url: https://github.com/lorepirri/jekyll-theme-simple-blog/tarball/master
