# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Simple Blog Theme
description: Simple Blog Theme is a clean, responsive blogging theme for Jekyll and GitHub Pages, with social/SEO features.
show_downloads: true
google_analytics:
# jekyll-theme-simple-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
jekyll-theme-simple-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

header:
  image: /assets/patterns/symphony.png

# social
author: "Lore Pirri"
image: /thumbnail-jumbo.png
twitter:
  username: lorepirri
#  site:
facebook:
  publisher: pirriontheroad
  profile_id: 1809805629
  app_id: 126080721296732
  authors: lorepirri
#  admins:
