# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Build Jekyll with Bundler on GitLab
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/jekyll-theme-simple-blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://lorepirri.gitlab.io" # change this to the base hostname & protocol for your site
twitter_username: lorepirri
github_username:  lorepirri

# Build settings
markdown: kramdown

# Make sure to exclude 'vendor' from the build
exclude: [vendor, "Gemfile", "Gemfile.lock"]

show_downloads: false

google_analytics:

# jekyll-theme-simple-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
jekyll-theme-simple-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

header:
  image: /assets/patterns/symphony.png

# social
author: "Lore Pirri"
image: /thumbnail-jumbo.png
twitter:
  username: lorepirri
#  site:
facebook:
  publisher: lorepirri
  profile_id: 1809805629
  app_id: 126080721296732
#  admins:
